/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'plr' at '11/14/15 6:58 PM' with Gradle 2.8
 *
 * @author plr, @date 11/14/15 6:58 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
