/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'plr' at '11/14/15 6:58 PM' with Gradle 2.8
 *
 * @author plr, @date 11/14/15 6:58 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
